### ISSUE TITLE
Cannot read files with variables bigger than 1GB

### ISSUE THREAD

**Issue by grabarczyk-t** [HebiRobotics/MFL#65]
When a variable in a file has more data than 1GB reading this file ends with exception:

```
Caused by: java.lang.IllegalArgumentException: buffer size <= 0
	at java.base/java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:86)
	at us.hebi.matlab.mat.types.AbstractSource.readInflated(AbstractSource.java:178)
	at us.hebi.matlab.mat.format.Mat5Reader.readEntry(Mat5Reader.java:270)
	at us.hebi.matlab.mat.format.Mat5Reader.readMatContent(Mat5Reader.java:228)
	at us.hebi.matlab.mat.format.Mat5Reader.readMat(Mat5Reader.java:194)
	... 70 more
```

This seem to be caused by integer overflow in `Mat5Reader.readEntry(Mat5Tag)`:

```
int bufferSize = Math.min(tag.getNumBytes() * 2, maxInflateBufferSize);
```

when getNumBytes is greater than 1073741823 multiplying it by two results in a negative value, it is set then to `bufferSize` which in turn causes the IllegalArgumentException

**Comment by ennerf** [comment]
Thanks for reporting this issue. I changed it to 

```
int bufferSize = tag.getNumBytes() * 2;
if (bufferSize > maxInflateBufferSize || bufferSize < 0 /* overflow >1 GB */) {
    bufferSize = maxInflateBufferSize;
}
```

and will do a new release sometime this week.

**Comment by grabarczyk-t** [comment]
Ok, great!

**Comment by ennerf** [comment]
Version 0.5.8 has been released. It may take a few hours to sync with sonatype.
